#spring.application.name=tickets-api

server:
  port: 0

spring:
  application:
    name: ticket-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: op[]
    url: jdbc:mysql://localhost:3306/airlines
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka